<?php

declare(strict_types=1);

namespace BetterCal\Support;

/**
 * Work budgets: how much of anything the app will take in one go.
 *
 * Entries here bound externally supplied input and aggregate work/output that
 * such input can trigger before it turns into parser memory, database writes,
 * worker starvation or browser work. They are not quotas on the owner; each
 * default is far above ordinary use, and the point is that a hostile or broken
 * input fails cleanly instead of taking a request, worker, import or tab down.
 *
 * One place, so an operator can see and tune all of them: each has an env
 * override (BETTERCAL_LIMIT_<NAME>, see .env.example), read by config() and
 * applied here once at startup. Static because the code that needs them is
 * mostly pure (Ics::parse, Filters matching) and has no config to be handed.
 */
final class Limits
{
    private const DEFAULTS = [
        // Text kept per event field. A description longer than this is cut, not
        // refused: a feed with one absurd event should still sync the rest.
        'DESCRIPTION_CHARS' => 65535,
        'URL_CHARS' => 2048,
        // One JSON API request. Calendar-file imports are multipart and keep
        // their own larger allowance below. This limit is enforced while the
        // stream is read, before json_decode builds a second object graph.
        'JSON_BODY_BYTES' => 1048576,    // 1 MiB
        // A calendar file someone uploads, and how many events it may hold.
        // Generous on purpose: a long-lived Google Calendar export is tens of
        // megabytes and well over ten thousand events, and importing one is
        // what this app is for. The count is further capped by the memory PHP
        // really has, see importEventBudget().
        'IMPORT_BYTES' => 26214400,      // 25 MiB
        'IMPORT_EVENTS' => 20000,
        // One operator-run Takeout migration. Files still commit one at a
        // time, but an accidentally selected export root cannot turn into an
        // unbounded filesystem walk/read job.
        'TAKEOUT_FILES' => 1000,
        'TAKEOUT_TOTAL_BYTES' => 1073741824, // 1 GiB of admitted .ics files
        // One subscribed feed, per poll. Parsing is bounded before it starts,
        // like an import: a hostile feed of tiny events otherwise exhausted the
        // worker's memory on every poll (scan 2026-09-23, F8). Also capped by
        // the memory PHP really has, see feedEventBudget().
        'FEED_EVENTS' => 20000,
        // One Google poll is a paginated, decoded JSON operation rather than
        // a single preflightable ICS file. Bound the complete operation — and
        // any stale-token retry — across items, decompressed bytes, pages and
        // elapsed time. googleEventBudget() lowers the item cap further when
        // the PHP process does not have enough memory for the pipeline's
        // concurrent decoded/parsed/database representations.
        'GOOGLE_SYNC_EVENTS' => 20000,
        'GOOGLE_SYNC_BYTES' => 33554432,       // 32 MiB cumulative
        'GOOGLE_SYNC_PAGES' => 20,
        'GOOGLE_SYNC_SECONDS' => 40,
        // Account calendar inventory is smaller, but is remote pagination too.
        'GOOGLE_CALENDAR_LIST_ITEMS' => 5000,
        'GOOGLE_CALENDAR_LIST_BYTES' => 5242880, // 5 MiB cumulative
        'GOOGLE_CALENDAR_LIST_PAGES' => 20,
        'GOOGLE_CALENDAR_LIST_SECONDS' => 20,
        // One outbound feed you publish. Calendar apps fetch it on their own
        // schedule and each fetch builds the whole file; over the cap the
        // oldest past events are left off first (#110).
        'OUTFEED_EVENTS' => 5000,
        'OUTFEED_BYTES' => 16777216,      // 16 MiB complete generated calendar
        'OUTFEED_RELATIONS' => 20000,
        // One recurrence-consuming operation, shared across every series it
        // visits. The per-series 1,000-instance guard remains a separate,
        // user-visible condition.
        'EXPANSION_SERIES' => 5000,
        'EXPANSION_OCCURRENCES' => 10000,
        'EXPANSION_SECONDS' => 8,
        'EVENT_WINDOW_BYTES' => 33554432, // 32 MiB of stored candidate text/JSON
        // An occurrence-targeted mutation proves that the supplied identity
        // is generated by the series. Keep the proof within a finite calendar
        // horizon even when a caller supplies an absurd timestamp.
        'RECURRENCE_MUTATION_HORIZON_DAYS' => 7305, // about 20 years either way
        // Plugins get smaller read/write snapshots than the interactive
        // calendar. Whole-snapshot syncs reject rather than truncate, because
        // truncation would delete the unseen tail.
        'PLUGIN_WINDOW_EVENTS' => 5000,
        'PLUGIN_SYNC_EVENTS' => 2000,
        'PLUGIN_SYNC_BYTES' => 8388608,   // 8 MiB of scalar input
        // Manual plugin runs are discretionary external work. Coalesce equal
        // jobs and keep both the rolling request rate and active queue small
        // enough that core calendar jobs cannot be buried behind them.
        'PLUGIN_MANUAL_RUNS_PER_HOUR' => 30,
        'PLUGIN_MANUAL_RUNS_PER_DAY' => 100,
        'PLUGIN_ACTIVE_JOBS' => 16,
        // One CalDAV object (one event plus its overrides) from a client.
        'DAV_OBJECT_BYTES' => 1048576,   // 1 MiB
        'DAV_OVERRIDES' => 500,
        // One incoming email, and the parts of it that get read.
        'MAIL_BYTES' => 5242880,         // 5 MiB, the whole message as the server reports it
        'MAIL_ICS_BYTES' => 1048576,     // 1 MiB per calendar part
        'MAIL_ICS_EVENTS' => 200,        // an invitation is one meeting plus its exceptions
        'MAIL_BODY_CHARS' => 524288,     // text/html handed to markup and LLM extraction
        // Public-mail aggregate budgets. Account-wide limits are the security
        // boundary because From, Message-ID and iCalendar UID are spoofable.
        'MAIL_EVENTS_PER_DAY' => 100,
        'MAIL_EVENTS_PER_SENDER_DAY' => 25,
        'MAIL_ACTIVE_EVENTS' => 500,
        // Open first-invitation and legacy-untrusted change candidates. Kept
        // below Review's 200-row read bound so public mail cannot bury every
        // genuine candidate behind an indefinitely growing queue.
        'MAIL_PENDING_INVITATIONS' => 100,
        'MAIL_LLM_PER_HOUR' => 20,
        'MAIL_LLM_PER_DAY' => 50,
        'MAIL_LLM_PER_SENDER_DAY' => 20,
        'MAIL_LOG_RETENTION_DAYS' => 90,
        // Outbound reminder/ad-hoc mail. These are attempt budgets: a failed
        // SMTP call still consumes its reservation so retry storms cannot
        // bypass the boundary. Push delivery remains independent.
        'NOTIFY_EMAILS_PER_CYCLE' => 50,
        'NOTIFY_EMAILS_PER_ACCOUNT_HOUR' => 100,
        'NOTIFY_EMAILS_PER_ACCOUNT_DAY' => 500,
        'NOTIFY_EMAILS_PER_RECIPIENT_HOUR' => 50,
        'NOTIFY_EMAILS_PER_RECIPIENT_DAY' => 200,
        'NOTIFY_EMAILS_PER_INSTALL_HOUR' => 200,
        'NOTIFY_EMAILS_PER_INSTALL_DAY' => 1000,
        // Other paid model entry points. Quick Add keeps an account ceiling
        // across sessions/tokens plus smaller per-token fairness limits;
        // prompt filters keep an account ceiling across all feed calendars.
        'MODEL_QUICKADD_CHARS' => 4000,
        'MODEL_QUICKADD_PER_HOUR' => 120,
        'MODEL_QUICKADD_PER_DAY' => 500,
        'MODEL_QUICKADD_PER_TOKEN_HOUR' => 30,
        'MODEL_QUICKADD_PER_TOKEN_DAY' => 150,
        'MODEL_QUICKADD_CONCURRENT' => 4,
        'MODEL_QUICKADD_PER_TOKEN_CONCURRENT' => 2,
        'MODEL_FILTER_PER_HOUR' => 40,
        'MODEL_FILTER_PER_DAY' => 200,
        'MODEL_FILTER_PER_CALENDAR_HOUR' => 20,
        'MODEL_FILTER_PER_CALENDAR_DAY' => 100,
        'MODEL_RESPONSE_BYTES' => 1048576, // authoritative streamed cap, all Gemini callers
        'MODEL_LOG_RETENTION_DAYS' => 90,
        // Duplicate detection is periodic heuristic work over externally
        // supplied events. Bound every slice before candidate generation can
        // become an all-pairs operation; unfinished rows continue in a later
        // worker job and pathological dense clusters are sampled, not fully
        // materialised as an O(n squared) graph.
        'DUPLICATE_SCAN_ROWS' => 500,
        'DUPLICATE_CANDIDATES_PER_EVENT' => 100,
        'DUPLICATE_LINKED_EDGES' => 5000,
        'DUPLICATE_LINK_TRAVERSAL_QUERIES' => 32,
        'DUPLICATE_OPEN_SUGGESTIONS' => 500,
        'DUPLICATE_OPEN_SUGGESTIONS_PER_EVENT' => 3,
        'DUPLICATE_COMPARISONS' => 20000,
        'DUPLICATE_PAIRS' => 2000,
        'DUPLICATE_SCAN_SECONDS' => 5,
        // Compact recurrence properties can hide thousands of comma-separated
        // values on one admitted line. Count them before parser/object work,
        // and keep one series from becoming a permanent expansion tax.
        'EXDATE_VALUES_PER_EVENT' => 1024,
        'EXDATE_VALUES_PER_INPUT' => 4096,
        // Regex filter evaluations per request or job, across all filters.
        'REGEX_EVALS' => 20000,
    ];

    /** Security ceilings: an operator may tune these budgets, but not remove the bound. */
    private const MAXIMUMS = [
        'JSON_BODY_BYTES' => 4194304,    // 4 MiB; unauthenticated requests reach this boundary
        'IMPORT_BYTES' => 104857600,
        'IMPORT_EVENTS' => 50000,
        'TAKEOUT_FILES' => 5000,
        'TAKEOUT_TOTAL_BYTES' => 4294967296,
        'GOOGLE_SYNC_EVENTS' => 50000,
        'GOOGLE_SYNC_BYTES' => 67108864,
        'GOOGLE_SYNC_PAGES' => 60,
        'GOOGLE_SYNC_SECONDS' => 45,
        'GOOGLE_CALENDAR_LIST_ITEMS' => 10000,
        'GOOGLE_CALENDAR_LIST_BYTES' => 20971520,
        'GOOGLE_CALENDAR_LIST_PAGES' => 60,
        'GOOGLE_CALENDAR_LIST_SECONDS' => 30,
        'OUTFEED_EVENTS' => 10000,
        'OUTFEED_BYTES' => 33554432,
        'OUTFEED_RELATIONS' => 50000,
        'EXPANSION_SERIES' => 10000,
        'EXPANSION_OCCURRENCES' => 25000,
        'EXPANSION_SECONDS' => 15,
        'EVENT_WINDOW_BYTES' => 67108864,
        'RECURRENCE_MUTATION_HORIZON_DAYS' => 18263, // about 50 years either way
        'PLUGIN_WINDOW_EVENTS' => 10000,
        'PLUGIN_SYNC_EVENTS' => 5000,
        'PLUGIN_SYNC_BYTES' => 16777216,
        'PLUGIN_MANUAL_RUNS_PER_HOUR' => 120,
        'PLUGIN_MANUAL_RUNS_PER_DAY' => 500,
        'PLUGIN_ACTIVE_JOBS' => 64,
        'MAIL_BYTES' => 26214400,        // 25 MiB; size preflight keeps headers/bodies behind this
        'MAIL_EVENTS_PER_DAY' => 500,
        'MAIL_EVENTS_PER_SENDER_DAY' => 100,
        'MAIL_ACTIVE_EVENTS' => 2000,
        'MAIL_PENDING_INVITATIONS' => 100,
        'MAIL_LLM_PER_HOUR' => 100,
        'MAIL_LLM_PER_DAY' => 250,
        'MAIL_LLM_PER_SENDER_DAY' => 100,
        'MAIL_LOG_RETENTION_DAYS' => 365,
        'NOTIFY_EMAILS_PER_CYCLE' => 250,
        'NOTIFY_EMAILS_PER_ACCOUNT_HOUR' => 500,
        'NOTIFY_EMAILS_PER_ACCOUNT_DAY' => 2000,
        'NOTIFY_EMAILS_PER_RECIPIENT_HOUR' => 250,
        'NOTIFY_EMAILS_PER_RECIPIENT_DAY' => 1000,
        'NOTIFY_EMAILS_PER_INSTALL_HOUR' => 1000,
        'NOTIFY_EMAILS_PER_INSTALL_DAY' => 5000,
        'MODEL_QUICKADD_CHARS' => 16000,
        'MODEL_QUICKADD_PER_HOUR' => 500,
        'MODEL_QUICKADD_PER_DAY' => 2000,
        'MODEL_QUICKADD_PER_TOKEN_HOUR' => 120,
        'MODEL_QUICKADD_PER_TOKEN_DAY' => 500,
        'MODEL_QUICKADD_CONCURRENT' => 12,
        'MODEL_QUICKADD_PER_TOKEN_CONCURRENT' => 6,
        'MODEL_FILTER_PER_HOUR' => 200,
        'MODEL_FILTER_PER_DAY' => 1000,
        'MODEL_FILTER_PER_CALENDAR_HOUR' => 100,
        'MODEL_FILTER_PER_CALENDAR_DAY' => 500,
        'MODEL_RESPONSE_BYTES' => 4194304,
        'MODEL_LOG_RETENTION_DAYS' => 365,
        'DUPLICATE_SCAN_ROWS' => 2000,
        'DUPLICATE_CANDIDATES_PER_EVENT' => 250,
        'DUPLICATE_LINKED_EDGES' => 20000,
        'DUPLICATE_LINK_TRAVERSAL_QUERIES' => 100,
        'DUPLICATE_OPEN_SUGGESTIONS' => 2000,
        'DUPLICATE_OPEN_SUGGESTIONS_PER_EVENT' => 10,
        'DUPLICATE_COMPARISONS' => 100000,
        'DUPLICATE_PAIRS' => 5000,
        'DUPLICATE_SCAN_SECONDS' => 10,
        'EXDATE_VALUES_PER_EVENT' => 2048,
        'EXDATE_VALUES_PER_INPUT' => 8192,
    ];

    /** @var array<string,int> */
    private static array $values = self::DEFAULTS;

    /** @return int the limit, always positive */
    public static function get(string $name): int
    {
        return self::$values[$name] ?? throw new \InvalidArgumentException("unknown limit: $name");
    }

    /**
     * Apply operator overrides. Unknown names and values below 1 are ignored:
     * a typo in .env must not turn a limit into "zero of everything".
     *
     * @param array<string,mixed> $overrides
     */
    public static function configure(array $overrides): void
    {
        foreach ($overrides as $name => $value) {
            if (isset(self::DEFAULTS[$name]) && is_numeric($value) && (int) $value >= 1) {
                self::$values[$name] = min((int) $value, self::MAXIMUMS[$name] ?? PHP_INT_MAX);
            }
        }
    }

    /** Measured: a parsed event costs about 8 KB of object graph; budget 12 KB for the rows built from it. */
    private const BYTES_PER_PARSED_EVENT = 12288;
    private const MEMORY_HEADROOM = 16777216; // 16 MiB left for everything else in the request
    // Google sync holds parsed changes, the prior snapshot and Feeds::sync's
    // database/index structures at once. A synthetic 5,000-item page measured
    // about 3 KiB/item for only raw+parsed shapes; 40 KiB plus 32 MiB headroom
    // conservatively bounds ordinary rows. Persisted text needs a second,
    // actual-size check: one maximum description can be much larger than the
    // per-item allowance even though it is individually valid.
    private const BYTES_PER_GOOGLE_EVENT = 40960;
    private const GOOGLE_MEMORY_HEADROOM = 33554432;
    private const GOOGLE_CACHED_ROW_OVERHEAD = 24576;
    private const GOOGLE_CACHED_PAYLOAD_COPIES = 3;

    /**
     * How many events an import may hold HERE: the configured cap, lowered to
     * what fits in this PHP process's memory_limit. Parsing is where an import
     * dies, and an out-of-memory fatal shows the owner a blank error; a number
     * they can act on ("this server can take about 9,000 events at once") is
     * the difference between a limit and a crash. Pure; unit-tested.
     *
     * @param ?string $memoryLimit php.ini memory_limit ("256M", "-1"); null reads it
     * @param ?int $usedBytes memory already in use; null reads it
     */
    public static function importEventBudget(?string $memoryLimit = null, ?int $usedBytes = null): int
    {
        $configured = self::get('IMPORT_EVENTS');
        $limit = self::iniBytes($memoryLimit ?? (string) ini_get('memory_limit'));
        if ($limit <= 0) {
            return $configured; // unlimited (-1), or unreadable: nothing to derive from
        }
        $free = $limit - ($usedBytes ?? memory_get_usage(true)) - self::MEMORY_HEADROOM;
        return max(100, min($configured, intdiv(max(0, $free), self::BYTES_PER_PARSED_EVENT)));
    }

    /** How many events one feed poll may parse here: FEED_EVENTS, lowered to what fits in memory. */
    public static function feedEventBudget(?string $memoryLimit = null, ?int $usedBytes = null): int
    {
        return min(self::get('FEED_EVENTS'), self::importEventBudget($memoryLimit, $usedBytes));
    }

    /** How many Google resources this process can safely carry through one poll. */
    public static function googleEventBudget(?string $memoryLimit = null, ?int $usedBytes = null): int
    {
        $configured = self::get('GOOGLE_SYNC_EVENTS');
        $limit = self::iniBytes($memoryLimit ?? (string) ini_get('memory_limit'));
        if ($limit <= 0) {
            return $configured;
        }
        $free = $limit - ($usedBytes ?? memory_get_usage(true)) - self::GOOGLE_MEMORY_HEADROOM;
        return max(0, min($configured, intdiv(max(0, $free), self::BYTES_PER_GOOGLE_EVENT)));
    }

    /**
     * Explain when materialising a cached Google snapshot is unsafe here.
     *
     * The database aggregate supplies the actual bytes in variable-width
     * columns. During a poll those strings can coexist in the PDO result,
     * parsed snapshot and Feeds index, so reserve three copies plus measured
     * per-row PHP-array overhead. The estimate is deliberately conservative:
     * refusing a poll keeps the prior calendar intact, while an OOM would kill
     * the shared worker before it could record the actionable error.
     */
    public static function googleSnapshotMemoryProblem(
        int $eventCount,
        int $payloadBytes,
        ?string $memoryLimit = null,
        ?int $usedBytes = null,
    ): ?string {
        $limit = self::iniBytes($memoryLimit ?? (string) ini_get('memory_limit'));
        if ($limit <= 0) {
            return null;
        }
        $available = $limit - ($usedBytes ?? memory_get_usage(true)) - self::GOOGLE_MEMORY_HEADROOM;
        $needed = max(0, $eventCount) * self::GOOGLE_CACHED_ROW_OVERHEAD
            + max(0, $payloadBytes) * self::GOOGLE_CACHED_PAYLOAD_COPIES;
        if ($available >= $needed) {
            return null;
        }
        return 'The cached Google calendar needs about ' . self::memoryMiB($needed)
            . ' MiB of working memory, but only ' . self::memoryMiB(max(0, $available))
            . ' MiB is safely available. Increase PHP memory_limit or reduce the calendar size;'
            . ' the existing calendar and sync position were kept unchanged.';
    }

    private static function memoryMiB(int $bytes): string
    {
        return number_format($bytes / 1048576, 1, '.', '');
    }

    /** "256M" -> bytes; "-1" and garbage -> 0 (no usable limit). */
    public static function iniBytes(string $value): int
    {
        if (preg_match('/^\s*(\d+)\s*([KMG]?)B?\s*$/i', $value, $m) !== 1) {
            return 0;
        }
        return (int) $m[1] * [1, 'K' => 1024, 'M' => 1048576, 'G' => 1073741824][strtoupper($m[2]) ?: 0];
    }

    /** @return list<string> */
    public static function names(): array
    {
        return array_keys(self::DEFAULTS);
    }

    public static function reset(): void
    {
        self::$values = self::DEFAULTS;
    }
}
