// Regenerates the <link rel="modulepreload"> block in web/index.html.
//
// This app ships unbundled ES modules on purpose (no build step). The cost of
// that is a discovery waterfall: the browser cannot know a module exists until
// it has fetched and parsed the one that imports it, and the graph is 11
// levels deep. Measured cold, that was ~610ms of the ~1.4s startup, spent
// almost entirely waiting rather than transferring.
//
// modulepreload tells the browser about every module up front, so it fetches
// the whole graph in parallel over the one HTTP/2 connection and the depth
// stops mattering. Generated rather than hand-listed so it cannot go stale —
// deploy.sh runs this before rsync and fails if the result is not committed.
//
//   node scripts/gen-preload.mjs [--check]

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const webDir = resolve(root, 'web');
const entry = resolve(webDir, 'src/app/main.js');
const indexPath = resolve(webDir, 'index.html');
const START = '  <!-- modulepreload:start (generated by scripts/gen-preload.mjs) -->';
const END = '  <!-- modulepreload:end -->';

// Walk the static import graph breadth-first, so the emitted order roughly
// matches the order the browser would have discovered them in anyway.
function graph(from) {
  const seen = new Set();
  const queue = [from];
  const order = [];
  while (queue.length) {
    const file = queue.shift();
    if (seen.has(file)) continue;
    seen.add(file);
    order.push(file);
    let src;
    try {
      src = readFileSync(file, 'utf8');
    } catch {
      continue;
    }
    // Static imports only: a dynamic import() is deliberately deferred, and
    // preloading it would undo that.
    for (const m of src.matchAll(/(?:^|\n)\s*(?:import|export)[^'"\n]*?from\s+'([^']+)'/g)) {
      const spec = m[1];
      if (!spec.startsWith('.')) continue;
      queue.push(resolve(dirname(file), spec));
    }
    for (const m of src.matchAll(/(?:^|\n)\s*import\s+'([^']+)'/g)) {
      if (m[1].startsWith('.')) queue.push(resolve(dirname(file), m[1]));
    }
  }
  return order;
}

const modules = graph(entry)
  .map((f) => '/assets/' + relative(webDir, f).split('\\').join('/'))
  // main.js already has its own <script> tag; preloading it too is wasted bytes.
  .filter((u) => !u.endsWith('/src/app/main.js'));

const block = [
  START,
  ...modules.map((u) => `  <link rel="modulepreload" href="${u}">`),
  END,
].join('\n');

const html = readFileSync(indexPath, 'utf8');
const hasBlock = html.includes(START);
const next = hasBlock
  ? html.replace(new RegExp(`${START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`), block)
  : html.replace('</head>', `${block}\n</head>`);

if (process.argv.includes('--check')) {
  if (next !== html) {
    console.error(`index.html preload block is stale (${modules.length} modules). Run: node scripts/gen-preload.mjs`);
    process.exit(1);
  }
  console.log(`preload block current (${modules.length} modules)`);
} else {
  writeFileSync(indexPath, next);
  console.log(`wrote ${modules.length} modulepreload links into web/index.html`);
}
