// Service worker strategy:
// - app shell (document, styles, every module, vendor): CACHE-FIRST, keyed
//   to VERSION. VERSION and SHELL are generated by scripts/gen-preload.mjs
//   from the module graph and a hash of every file in it, so a deploy that
//   changes anything gets a new version (a new cache, the old one deleted on
//   activate) and a deploy that changes nothing invalidates nothing. The
//   browser re-fetches sw.js itself on every navigation (nginx: no-cache),
//   which is how a new version is noticed.
// - a new version, once active, tells open pages so they can offer a reload;
//   until they do they keep running what they loaded, which is always a
//   consistent set.
// - API GETs: network-first with a 5s timeout falling back to cache.
//
// Why cache-first: unbundled modules are ~75 requests. Network-first with
// forced revalidation made every one of them a round trip before the app
// could start, which on a 450 ms link was nine seconds of a blank page.

// @generated-shell:start (scripts/gen-preload.mjs)
const VERSION = 'bc-e7faeccf27ea';
const SHELL = [
  '/',
  '/assets/styles/app.css',
  '/assets/manifest.webmanifest',
  '/assets/icons/icon.svg',
  '/assets/icons/icon-maskable.svg',
  '/assets/icons/icon-192.png',
  '/assets/icons/icon-512.png',
  '/assets/vendor/leaflet/leaflet.js',
  '/assets/vendor/leaflet/leaflet.css',
  '/assets/vendor/leaflet/images/marker-icon.png',
  '/assets/vendor/leaflet/images/marker-icon-2x.png',
  '/assets/vendor/leaflet/images/marker-shadow.png',
  '/assets/vendor/squire/purify.min.js',
  '/assets/vendor/squire/squire-raw.js',
  '/assets/src/app/main.js',
  '/assets/vendor/index.js',
  '/assets/src/app/App.js',
  '/assets/src/app/store.js',
  '/assets/src/app/actions.js',
  '/assets/src/app/api.js',
  '/assets/src/app/system.js',
  '/assets/src/app/prefetch.js',
  '/assets/src/app/RichText.js',
  '/assets/src/app/EventDetail.js',
  '/assets/src/lib/dates.js',
  '/assets/src/app/push.js',
  '/assets/vendor/preact.module.js',
  '/assets/vendor/htm.module.js',
  '/assets/src/ui/grouping.js',
  '/assets/src/lib/rank.js',
  '/assets/src/app/keyboard.js',
  '/assets/src/ui/monthmath.js',
  '/assets/src/ui/MonthGrid.js',
  '/assets/src/ui/TimeGrid.js',
  '/assets/src/ui/AgendaList.js',
  '/assets/src/lib/quickcreate.js',
  '/assets/src/ui/DayExpand.js',
  '/assets/src/ui/RescheduleMode.js',
  '/assets/src/app/Toolbar.js',
  '/assets/src/app/Sidebar.js',
  '/assets/src/app/QuickAdd.js',
  '/assets/src/app/EventPopover.js',
  '/assets/src/app/GroupPopover.js',
  '/assets/src/app/EditorDrawer.js',
  '/assets/src/app/CreateDrawer.js',
  '/assets/src/app/SearchOverlay.js',
  '/assets/src/app/ShortcutsSheet.js',
  '/assets/src/app/CommandPalette.js',
  '/assets/src/app/Toasts.js',
  '/assets/src/app/Login.js',
  '/assets/src/app/OutfeedsPage.js',
  '/assets/src/app/FiltersPage.js',
  '/assets/src/app/SavedViewsPage.js',
  '/assets/src/app/SettingsPage.js',
  '/assets/src/app/PeoplePage.js',
  '/assets/src/app/ActivityPage.js',
  '/assets/src/app/OrganizePage.js',
  '/assets/src/app/PluginsPage.js',
  '/assets/src/app/ProposalsPage.js',
  '/assets/src/lib/richtext.js',
  '/assets/src/app/settings.js',
  '/assets/src/ui/trips.js',
  '/assets/src/lib/since.js',
  '/assets/src/lib/maps.js',
  '/assets/src/app/Trips.js',
  '/assets/src/ui/icons.js',
  '/assets/src/ui/EventChip.js',
  '/assets/src/lib/reminders.js',
  '/assets/src/app/EventPluginData.js',
  '/assets/src/app/PageShell.js',
  '/assets/src/lib/deeplink.js',
  '/assets/src/app/hotkeys.js',
  '/assets/src/ui/layout.js',
  '/assets/src/ui/DragController.js',
  '/assets/src/lib/color.js',
  '/assets/src/app/ViewSwitcher.js',
  '/assets/src/app/JumpPopover.js',
  '/assets/src/app/CalendarSettings.js',
  '/assets/src/app/MiniMonth.js',
  '/assets/src/app/commanddefs.js',
  '/assets/src/app/PlaceInput.js',
  '/assets/src/app/PeopleInput.js',
  '/assets/src/app/commands.js',
  '/assets/src/lib/fuzzy.js',
  '/assets/src/lib/jumpparse.js',
  '/assets/src/app/SchemaForm.js',
  '/assets/src/lib/minimonth.js',
];
// @generated-shell:end

const SHELL_CACHE = VERSION + '-shell';
const API_CACHE = VERSION + '-api';
const API_TIMEOUT_MS = 5000;

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL_CACHE);
    // Bypass the HTTP cache: this is the one moment the worker must see the
    // server's current files, not a 30-day immutable copy of the old ones.
    // One missing icon must not block an update, so entries fail alone.
    await Promise.all(SHELL.map(async (u) => {
      try {
        const res = await fetch(new Request(u, { cache: 'reload' }));
        if (res.ok) await cache.put(u, res);
      } catch { /* fetched on demand later */ }
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => !k.startsWith(VERSION)).map((k) => caches.delete(k)));
    await self.clients.claim();
    // Pages already open loaded the previous version; let them offer a reload.
    const clients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    for (const c of clients) c.postMessage({ type: 'sw-updated', version: VERSION });
  })());
});

function networkFirstWithTimeout(request, cacheName, timeoutMs) {
  return new Promise((resolve) => {
    let settled = false;
    const timer = timeoutMs ? setTimeout(async () => {
      const cached = await caches.match(request);
      if (cached && !settled) { settled = true; resolve(cached); }
    }, timeoutMs) : null;
    fetch(request).then(async (res) => {
      if (timer) clearTimeout(timer);
      if (res.ok) {
        const cache = await caches.open(cacheName);
        cache.put(request, res.clone());
      }
      if (!settled) { settled = true; resolve(res); }
    }).catch(async () => {
      if (timer) clearTimeout(timer);
      const cached = await caches.match(request);
      if (!settled) {
        settled = true;
        resolve(cached || new Response(JSON.stringify({ error: { code: 'offline', message: 'Offline and not cached' } }), {
          status: 503,
          headers: { 'Content-Type': 'application/json' },
        }));
      }
    });
  });
}

// Shell: the versioned cache answers; anything not precached (a lazily
// loaded file, a query-string variant) is fetched once and kept. ignoreSearch
// so /assets/styles/app.css?v=3 and the bare path are one entry.
async function cacheFirst(request) {
  const cached = await caches.match(request, { ignoreSearch: true });
  if (cached) return cached;
  const res = await fetch(request);
  if (res.ok) {
    const cache = await caches.open(SHELL_CACHE);
    cache.put(request, res.clone());
  }
  return res;
}

// --- Web Push reminders -----------------------------------------------------
// The worker sends {title, body, url, tag}; tag replaces earlier notifications
// for the same occurrence instead of stacking duplicates.

self.addEventListener('push', (event) => {
  let data = {};
  try {
    data = event.data ? event.data.json() : {};
  } catch (e) {
    data = { body: event.data ? event.data.text() : '' };
  }
  event.waitUntil(self.registration.showNotification(data.title || 'Better-Cal', {
    body: data.body || '',
    tag: data.tag || undefined,
    icon: '/assets/icons/icon-192.png',
    badge: '/assets/icons/icon-192.png',
    data: { url: data.url || '/' },
  }));
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const url = (event.notification.data && event.notification.data.url) || '/';
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((list) => {
      for (const client of list) {
        if (new URL(client.url).origin === self.location.origin && 'focus' in client) {
          client.focus();
          return 'navigate' in client ? client.navigate(url) : undefined;
        }
      }
      return clients.openWindow(url);
    }),
  );
});

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== location.origin) return;

  if (url.pathname.startsWith('/api/')) {
    event.respondWith(networkFirstWithTimeout(event.request, API_CACHE, API_TIMEOUT_MS));
    return;
  }

  // The document for any app path ('/', '/add', '/subscribe', ...) is the
  // one cached shell document; deep-link paths are read by the app itself.
  if (event.request.mode === 'navigate') {
    event.respondWith(cacheFirst(new Request('/')).catch(() => fetch(event.request)));
    return;
  }

  if (url.pathname.startsWith('/assets/')) {
    event.respondWith(cacheFirst(event.request));
  }
});
